<template>
<div>
  <table class="table table-hover tbl" >
    <tbody>
      <tr class="table-light wobble-hor-bottom" v-for="cart in carts" :key="cart._id">
        <th scope="row"> {{ cart.title }}</th>
        <td> {{ cart.quantity }}</td>
        <td>{{ cart.price }} <i class="fa fa-trash-o" @click="removeItem(cart)"></i> </td>
      </tr>
      <!-- total cart -->
      <tr class="table-primary">
        <td> <button type="button" class="btn btn-info btn-sm wd" @click="checkout">Checkout</button> </td>
        <td> <button type="button" class="btn btn-danger btn-sm" @click="cancel">cancel</button> </td>
        <th scope="row" class="ttl">IDR {{ total }}</th>
      </tr>
    </tbody>
  </table>
</div>
</template>

<script>
import { mapState, mapMutations } from 'vuex'
export default {
  computed: {
    ...mapState([
      'carts',
      'total'
    ])
  },
  methods: {
    ...mapMutations([
      'cancel',
      'removeItem',
      'checkout'
    ])
  }
}
</script>

<style scoped>
.tbl {
  margin-top: 2%;
}

.fa {
  font-size:16px;
  color:red;
  cursor: pointer;
}

.wd {
  width: 120%;
}

.ttl {
  padding-left: 0%;
  padding-bottom: 6px;
}

.wobble-hor-bottom {
  -webkit-animation: wobble-hor-bottom 0.8s both;
        animation: wobble-hor-bottom 0.8s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2018-2-21 0:30:59
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-hor-bottom
 * ----------------------------------------
 */
@-webkit-keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
            transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
            transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
            transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
            transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
            transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
            transform: translateX(-6px) rotate(-1.2deg);
  }
}
@keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
            transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
            transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
            transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
            transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
            transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
            transform: translateX(-6px) rotate(-1.2deg);
  }
}
</style>
