<template>
  <div class="container-fluid">
    <div class="row">
      <div class="card mb-3 col-md-4 bd slide-in-left" v-for="paint in paints" :key="paint._id">
        <div class="card-body ct-p">
          <h5 class="card-title">{{ paint.title }}</h5>
        </div>
        <img :src="paint.image" alt="Card image">
        <div class="card-body">
          <p class="card-text">{{ paint.description }}</p>
          <div class="flx-btn">
            <h5>IDR {{ paint.price }}</h5>
            <button @click="addToCart(paint)" type="button" class="btn btn-success btn-sm">Add To Cart</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { mapState, mapMutations } from 'vuex'
export default {
  computed: {
    ...mapState([
      'paints',
      'searching'
    ])
  },
  methods: {
    ...mapMutations([
      'addToCart'
    ]),
    filteredPaint () {
      console.log(this.searching)
      return this.paints.filter(paint => {
        return paint.title.match(this.searching)
      })
    }
  }
}
</script>

<style scoped>
.flx-btn {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
}

h5 {
  margin: 0%;
}

.bd {
  border: 1px solid #666;
}

img {
  height: 150px;
  width: 100%;
  display: block;
}

.row {
  margin-top: 1%;
}

.ct-p {
  padding: 15px 10px 5px 10px;
}

button {
  padding: 3px 15px;
}

.slide-in-left {
  -webkit-animation: slide-in-left 2.0s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        animation: slide-in-left 2.0s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-2-21 0:33:42
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
</style>
